[workspace]
resolver = "3"
members = [
    "tiktok",
    "tiktok-cli",
    
    "tikwm",
    "tikwm-cli",
]

[profile.release]
lto = "fat"
opt-level = 3
codegen-units = 1
panic = "abort"
strip = "symbols"
